---
title: "First Knit"
author: "Adam Ayala"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can 
get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. yes this is amazing

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended the high school called Lancaster High School. Lancaster high school had a lot of new things being added to it when I was attending. So much so that all my teachers were calling us lucky since they would have never dreamed of having what we had. I was able to graduate the year 2022 as a valedictorian. I also got a necklace for the bio medical pathway that was available at the school, which congratulated me for 4 years of staying in the program. Math is easier for me as it is more simple and straight to the point. English needs analysis and requires opinion, math is absolute. Due to these differences math was easier for me to grasp since their was really only one way to learn, of course there is multiple ways to solve a problem but that way has to be the same all the time. English at times seemed tedious since I had to find specific reasons or just reasons my teacher or professor agrees with and write that.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a windows computer that may be 8 years old but works amazingly. The reason for this is because it is my brothers old gaming computer that was top of the line at the time of buying it and for me it runs beautifully. However some games do run slowly which is where the age shows. I would give myself a 3 since I know very little computer lingo or even how to properly maintain my computer. I know words here and there since I have seen videos that make fun of people who mess up with a computer and I watch and learn so I don't do that. But it is more surface level knowledge like what Ram is. I have wifi at my house as without it I wouldn't be able to game, but on a serious note wifi seems essential at this point. The wifi in  my house is very strong since 5 different people at the same time are online forcing us to buy a stronger wifi. Maybe my family is just acting spoiled but we do have limits.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  The name I prefer being called is by my legal first name which is Adam. Some of my buddies call me names such as Ayaya, making fun of my last name because they couldn't say it. Other names include Diego because someone said I look like a Diego. For the people in class I would stick with Adam but if I had to change it I would feel embarressed but I'll say Silver since it what I call myself online.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   In life their is not much I want to achieve, I say 1 thing matters the most and the other 2 are future endeavors. The most important thing for me is my relationship with God, as I do believe in God, the son and the holy spirit with Jesus the son being our lord and savior. That to me is the most important and I wish to continue this endeavor, and the next 2 things including my career and fun. Which leads into the college subject of greatest interest being Biology as I want to be a heart surgeon which my next aspiration. I have always been interested in the human body and the heart is the most interesting and covers a lot of ideas I am interested in. I hope to achieeve my associates in Biology for transfer as a result of my career choice. With this transfer degree I hope to get my bachelors and get into med school.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I have never visited a foreign country before, I have been to different states such as Neveda and San Francisco. San Franscio being my favorite because I went to Universal Orlando and that was an unforgettable experience. Countries I may want to visit is Japan mainly because of all the videos I see of their unique technology. The next is probably somewhere in Europe to see a famous place like the effiel tower, the collesium or the leaning tower. But mainly to experience a different kind of culture as the little I've seen from differnt states I can imagine the difference in countries. I have never been in the military and the branch I would choose if I had to serve would probably be the army. Although I can't be sure of that, I was in AFJROTC in high school so I have some exposure to military discipline and the Air Force. But I did see the movie Hacksaw Ridge which also left a big impact on me.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I have never taken a statistics class before and Math 116 is my first. Math 116 is interesting since it focuses less as a math class and more as a program class. But they could be the same in the fact of learning a method to figure out a situation. I did not know that Math 116 counts as statistics over math 115. I have to take this class as a transfer requirement, meaning programs must be more important in identifying information of the mathematical process. The grade I need is passing, however low grades affect my GPA and make me seem less competitive. Ideally an A to keep my GPA up and to also learn what is needed for the university I transfer to. My career plan is to become a Heart Surgeon, to do so I must go to med school after obtaining my bachelors and then go into residency regarding my profession. And if need be do a refresher course as apparently that is best if a doctor wants to get hired. I think it might be a case by case situation.
 






  




